name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # 或者你需要的 Node.js 版本

      - name: Run build script
        run: |
          npm install
          npm run build
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          echo "@ruxuwu:registry=https://registry.npmjs.org/" >> .npmrc
          npm publish --access public
        working-directory: packages/jin
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
